//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DosLenguas {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class propiedades : global::System.Configuration.ApplicationSettingsBase {
        
        private static propiedades defaultInstance = ((propiedades)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new propiedades())));
        
        public static propiedades Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\hernani\\Documents\\Lear_Inglish\\Sound")]
        public string dirsound {
            get {
                return ((string)(this["dirsound"]));
            }
            set {
                this["dirsound"] = value;
            }
        }
    }
}
